name: Pylint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-dev \
          libgl1-mesa-glx \
          libgles2-mesa \
          libsdl2-dev \
          libsdl2-image-dev \
          libsdl2-mixer-dev \
          libsdl2-ttf-dev \
          libportmidi-dev \
          libswscale-dev \
          libavformat-dev \
          libavcodec-dev \
          zlib1g-dev \
          gstreamer1.0-plugins-base \
          gstreamer1.0-plugins-good
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install pylint
        python -m pip install kivy
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
